### PR TITLE
Fixing your sabotages

### PR DESCRIPTION
**Pull request by derekthesnake**
This PR includes fixes for all the sabotages! GitHub Actions tests should all pass.

### CODE REVIEW

**Comment by derekthesnake** [comment]
This is Team 4's version of fixing your sabotages btw

**Review by FernandoGV667 — APPROVED** [review]
It passes all the tests, so it's approved, but  you removed my move algorithm to try to stabilize movements

**Review by sukhmank11 — APPROVED** [review]
Looks good, fixes work

**Review by nate-perry — APPROVED** [review]

**Review by chs-mix — APPROVED** [review]
looks fine to me

**Pull request merged**
